# Generated by Django 3.0.7 on 2020-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='structures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('smiles', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='structure',
        ),
    ]
