# Generated by Django 3.0.7 on 2020-06-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0002_auto_20200615_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='structures',
            name='author_name',
            field=models.CharField(choices=[('ENDIKA', 'Endika'), ('RAI', 'Rai')], default='name', max_length=10),
        ),
        migrations.AddField(
            model_name='structures',
            name='project_name',
            field=models.CharField(choices=[('PANCREAS', 'PanTCK'), ('ZAP', 'ZAP')], default='project', max_length=10),
        ),
    ]
