# Generated by Django 3.0.7 on 2020-06-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0003_auto_20200615_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='structures',
            new_name='structure',
        ),
    ]
